const routes = {
    home: '/',
    search: '/search',
    product: '/product',
    profile: '/profile/:userId',
    productDetail: '/product/:productId',
    updateProduct: '/updateProduct/:productId',
    addProduct: '/addProduct',
    // carts: '/carts',
    carts: '/carts/:id',
    checkout: '/checkout',
    admin: '/admin',
    login: '/login',
    order: '/order',
    address: '/address',
    category: '/category/:categoryId',
    register: '/register',
    forgotpassword: '/forgot-password',
    news : '/news',
    addNew : '/addNew',
    updateNew : '/updateNew/:bannerId',
    sales : '/sales',
    addSale: '/addSale',
    updateSale: '/updateSale/:saleId',
    vnpay : '/vnpay/',
    // method : '/payment-method',
    deletemany : '/delete-many',

};

export default routes;
